version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: devpassword
    volumes:
      - ./data/dev/db:/var/lib/postgresql/data

  api:
    build:
      context: ./server/GigaChat
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=my_db;Username=postgres;Password=devpassword"
    ports:
      - 5000:80
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:80
